version: '{build}'
image: Visual Studio 2017
configuration: Release

install:
- cmd: git submodule update --init --recursive
- cmd: nuget restore

build:
  project: Hotsapi.Uploader.sln
  verbosity: minimal

artifacts:
- path: Releases\HotsApiUploaderSetup.exe

cache:
  - packages -> **\packages.config

